### ISSUE TITLE
Test on other browsers / platforms

### ISSUE THREAD

**Issue by xaranke** [enjalot/building-blocks#17]
Here are some issues I encountered with cross-browser testing:

1) On Safari 8.0.7 on OS X 10.10.4, scrolling through the code doesn't expand the code view.

2) On Firefox 39.0.3 on OS X 10.10.4, the scrolling for the code box works but the focus doesn't reset to the result view on hover.

There are potentially more that I haven't found, so feel free to leave a comment on this PR if you find other bugs. Thanks!

**Comment by enjalot** [comment]
I just pushed a fix for the hover problem in firefox. I don't see an issue in safari over here, can you recheck it? I'm going to close, but lets open new issues for any problems we encounter on a case by case basis. 
thanks!
