### ISSUE TITLE
improve file adding/editing UX

### ISSUE THREAD

**Issue by enjalot** [enjalot/building-blocks#31]
Because we count on loading the raw data from github our edits aren't immediate, and that isn't obvious.

If you add data.json to the block via the file adding UI, it will save and reload the page. Let's say you have an error in the json file, or want to edit it slightly. Edits will seem like they are refreshing the display, but aren't actually doing anything. If you click save and reload the page you will see the results, but that sucks.

## potential hacky but seamless solution
hijack d3.ajax and short-circuit the function to return text found in the file contents rather than a real ajax request.
This would mean injecting some javascript after d3 is loaded but before the user code is run... and would only work with d3 function calls. If this solution breaks for some reason it would be very unclear to the user why their code is broken.

## worse UX but simpler solution
Make it very clear in the UI that editing files requires a roundtrip. Make it easy for the user to save+refresh from the file editing ui?

**Comment by enjalot** [comment]
Another solution is a proxy. Something I'd really like to avoid because of its vulnerability to abuse and the maintenance required.
It may be a more attractive option because allowing external style sheets via the <link rel="style.css"> requires yet another messy regex like https://github.com/enjalot/building-blocks/blob/master/public/js/utils/parseCode.js#L22
that's more fragile than the way people normally include scripts...

A proxy would not solve the immediate feedback issue of editing a file, but it would be more reliable way to give access to the files.

**Comment by enjalot** [comment]
I've gone ahead and implemented the regex for supporting css files: https://github.com/enjalot/building-blocks/blob/master/public/js/utils/parseCode.js#L32

It's still fragile but should work in most cases... one of the benefits of doing things this way (with the file contents) is that it makes things live-reload when you edit them (you can edit the styles and see the results immediately). something I'm not sure how we would do with a proxy.

**Comment by enjalot** [comment]
I solved this thanks to a recommendation from @vicapow to overload the XMLHttpRequest object:
https://github.com/enjalot/building-blocks/blob/master/public/js/utils/parseCode.js#L67

we can now add files and edit them locally and see the changes reflected live. we only need to save when we are ready, resulting in a normal and expected UX!

**Comment by vicapow** [comment]
👏👏👏
