### ISSUE TITLE
error handling when js is in separate file

### ISSUE THREAD

**Issue by peterbsmith2** [enjalot/building-blocks#38]
[This gist](http://gist.github.com/peterbsmith2/a37f2b733a75a6f348c2) loads fine in [bl.ocks](http://bl.ocks.org/peterbsmith2/a37f2b733a75a6f348c2) but not in the [demo](http://demo.ian.codes/peterbsmith2/a37f2b733a75a6f348c2) because d3 code is in separate js.  
  
If functionality isn't in roadmap to support loading files outside of index.html, an error should be thrown.

**Comment by enjalot** [comment]
you have indeed found a weakness in my support of external js files. this version does work:
http://demo.ian.codes/enjalot/b88142bcdded00c62083

I'll need to make this a bit more robust!

**Comment by peterbsmith2** [comment]
how the heck? well kudos to the work you've done, its an awesome project

**Comment by enjalot** [comment]
it's this regex that needs to be improved to handle the case you found:
https://github.com/enjalot/building-blocks/blob/master/public/js/utils/parseCode.js#L22

this example also breaks for the same reason (but a different case) http://bl.ocks.org/syntagmatic/c7d6ea0132c956140cbb
