### ISSUE TITLE
Text editor should have a certain minimum height at all times even if its empty

### ISSUE THREAD

**Issue by shobhitg** [enjalot/building-blocks#39]
The text editor should not rely upon newline characters for its height. And it should have a minimum height even if there is no content.

When the file is only 2 or 3 lines, then it becomes quite difficult to work with it.

**Comment by enjalot** [comment]
you are absolutely right. I just used new lines out of laziness to get things going. We should be able to accomplish this with pure CSS i hope.

**Comment by shobhitg** [comment]
https://github.com/shobhitg/building-blocks/commit/ecd9d5d20a137cc70d0f1abc6ee8d9957b72de99

You are right, css did it. Cherry-pick from here if it looks good.

**Comment by enjalot** [comment]
thanks!
