### ISSUE TITLE
Building blocks is already nice and useable

### ISSUE THREAD

**Issue by shobhitg** [enjalot/building-blocks#40]
It will find skyrocketing beta adoption if its demo could be permanently hosted as well which could be updated with the most stable version (based on npm semver's minor digit).

Lets discuss ideas around this topic.

**Comment by enjalot** [comment]
I agree, I'm using a lot of will power to not release it as is! The alpha session at the meetup was very helpful, and it proved that it is already immensely useful.

I just really want to make sure the backers are recognized when it goes out. I've gotten most of the survey responses, so If I can quickly add them to the page I'll at least launch to backers this week.

I will also setup some sort of status wiki on the repo that we can use to document edge cases & work arounds while it is still in beta.

**Comment by enjalot** [comment]
I'm going to launch this to backers tonight!

**Comment by curran** [comment]
Woohoo! Congrats. Can't wait to use it.
