### ISSUE TITLE
Cannot scroll README

### ISSUE THREAD

**Issue by mgold** [enjalot/building-blocks#43]
I'm looking at the Matrix: Reboot example, and the README is just barely too long to fit in the rendered markdown view panel. When I try to scroll, the source area scrolls up over the README. I would like some way to see the entire rendered markdown.

**Comment by enjalot** [comment]
good call. found a way to reliably make it scroll. previously react was messing with me because it would turn scrolling="no" to scrolling without rerendering the iframe, so the browser did not respect the change.
