### ISSUE TITLE
Slider widget 'sticks' when switching between standard and side-by-side view

### ISSUE THREAD

**Issue by brylie** [enjalot/building-blocks#45]
# Description
The slider widget stays on the screen when clicking a numeric value in standard mode and then switching to side-by-side mode.

# Steps to reproduce
1. View a [project](http://blockbuilder.org/enjalot/476c804335f77198447e)
1. click a numeric value (such as font-size, width, margin-top, etc)
1. switch a to side-by-side mode

# Observed behavior
The slider widget stays visible on the page, and can not be cleared.
![sticky-slider-widget](https://cloud.githubusercontent.com/assets/17307/9625908/4a18619c-5162-11e5-91f2-f18551b555bb.jpeg)

# Expected behavior
The slider widget should be cleared from the page.

# Environment
I am using Firefox 40.0.3 on Xubuntu 15.04.

**Comment by enjalot** [comment]
I fixed this in the referenced commit ^

**Comment by enjalot** [comment]
Thanks for the thorough bug report!
