### ISSUE TITLE
Block output not automatically updating with code changes

### ISSUE THREAD

**Issue by brylie** [enjalot/building-blocks#46]
# Description
When making a code change in a block example, the display does not update to reflect new changes.

# Steps to reproduce
1. View a [project](http://blockbuilder.org/enjalot/476c804335f77198447e)
1. make a code change

# Observed behavior
The rendered result stays the same until some page event, such as switching to side-by-side mode, causes re-render.

# Expected behavior
The rendered output should change to reflect the state of the code, or the user should be encouraged to manually refresh the output.

# Environment
I am using Firefox 40.0.3 on Xubuntu 15.04.

**Comment by enjalot** [comment]
thanks, this turned out to be stupid stray return that i put in while debugging... pushed a fix!
