### ISSUE TITLE
noZero decimal not managed correctly when Inlet driven below 0

### ISSUE THREAD

**Issue by mr23** [enjalot/building-blocks#47]
See sample at http://blockbuilder.org/mr23/f50b395446ecbc1a25e9
or just drive the slider for noZero below zero.
For example, it results in : 
.-41
instead of
-.41

**Comment by enjalot** [comment]
this has been fixed in the [Inlet](https://github.com/enjalot/Inlet) project which powers the sliders. thanks for filing the issue!
