### ISSUE TITLE
external JS files should be edited in CodeMirror

### ISSUE THREAD

**Issue by enjalot** [enjalot/building-blocks#49]
I made all files that weren't the index.html or README.md editable via HTML5 textarea rather than using CodeMirror. This is mostly to avoid performance problems when trying to render large csv or json files. For external code files we should easily be able to support new editor instances (e.g. for .js or .coffee, maybe even .jsx, .jade etc) 

You can see how the editor components are loaded dynamically depending on which file is being used:
https://github.com/enjalot/building-blocks/blob/master/public/js/components/editor.js#L50

the implementations for HTML: https://github.com/enjalot/building-blocks/blob/master/public/js/components/editor__html.js  
Markdown: https://github.com/enjalot/building-blocks/blob/master/public/js/components/editor__md.js

**Comment by curran** [comment]
This is awesome. Thank you so much for adding this. I just tried out the feature, it works great!
