### ISSUE TITLE
consider removing handlebars?

### ISSUE THREAD

**Issue by vicapow** [enjalot/building-blocks#5]
Handlebars doesn't seem like it's used for much. remove?

https://github.com/enjalot/building-blocks/blob/master/views/base.handlebars#L1

**Comment by enjalot** [comment]
yeah, it's not actively used for anything right now since I'm getting everything i need clientside. I left it in just in case I'm missing something. I will probably refactor it out once I've completed the rest of the routes and its still not used.

**Comment by enjalot** [comment]
I'm now using handlebars to selectively add google analytics tracking based on server-side configuration. Going to keep it around for the time being!
