### ISSUE TITLE
Ability to upload more files (not just text)

### ISSUE THREAD

**Issue by jkutianski** [enjalot/building-blocks#53]
Building-blocks don't allows me to upload a second JS file or a JSON file.
On this http://bl.ocks.org/jkutianski/0601ad01f560d49a5967 I can't upload d3.selection.template.min.js and on this https://gist.github.com/jkutianski/6591596 I can't upload argentina_indec.json file.

**Comment by mostaphaRoudsari** [comment]
I would add csv file to the list. Changing *.csv to *.txt solved the issue but is not a clean approach.

**Comment by enjalot** [comment]
Strange, all of those file types are supported and Ive uploaded multiple
files. i will try to reproduce with those gists.

can you upload the csv that didnt work somewhere for me to test with too?

**Comment by mostaphaRoudsari** [comment]
Sure! This one: http://bl.ocks.org/mbostock/1667367

**Comment by enjalot** [comment]
Just for clarification, do you mean a second file with the same name? In this case building-blocks will overwrite the first. Can you give a little more detail on your steps to reproduce @jkutianski? Were you starting from a fresh block or forking one of those?

**Comment by jkutianski** [comment]
I started a new one and i've to upload a CSV and TopoJSON.

**Comment by mostaphaRoudsari** [comment]
@enjalot in may case I just needed to use it to show to someone the process very quickly so I just copy-pasted the code into index.html and then tried to add a new data file.

**Comment by enjalot** [comment]
I'm starting to suspect this isn't actually broken, just a symptom of bad UI/UX. I've pushed a fix that makes it much more obvious what happens when adding a file. I'm going to close this, but please reopen if you still can't add these files. Also please check the console to see if there are any error messages that can help.
