### ISSUE TITLE
data-tip obscured for block__site-nav & block__mode 

### ISSUE THREAD

**Issue by kenpenn** [enjalot/building-blocks#55]
Probably need to up the z-index for tooltips for divs block__site-nav & block__mode 
<img width="122" alt="screen shot 2015-09-20 at 12 40 23 pm" src="https://cloud.githubusercontent.com/assets/294968/9982678/e68123a4-5f98-11e5-921f-3f6975752d02.png">
<img width="142" alt="screen shot 2015-09-20 at 12 39 56 pm" src="https://cloud.githubusercontent.com/assets/294968/9982679/ed655dca-5f98-11e5-938a-7e28b45f4bbd.png">

**Comment by enjalot** [comment]
fixed! thanks
