### ISSUE TITLE
Text editing in browser

### ISSUE THREAD

**Issue by jalapic** [enjalot/building-blocks#56]
I have tried  using simple plugin extensions for chrome like "Search & Replace" to be able to do basic tasks like finding a name and replacing all instances with a new name.  Unfortunately these don't work to well (at least in my hands).  Would be great to know how to maybe implement some extra text editor capabilities. Thanks.

**Comment by enjalot** [comment]
It appears that search-and-replace is supported by codemirror, but that the short-cut keys are really weird:
https://codemirror.net/demo/search.html

`Cmd-Option-F` brings up an interface for replacing things 1 by 1
`Shift-Cmd-Option-F` will replace all

This does need to be enabled in the code via the search plugin, but it is already included in CodeMirror so it shouldn't be hard to do
