### ISSUE TITLE
Syntax error line numbers

### ISSUE THREAD

**Issue by georules** [enjalot/building-blocks#59]
<img width="1503" alt="screen shot 2015-10-13 at 3 35 43 pm" src="https://cloud.githubusercontent.com/assets/775628/10466063/22e6b550-71c0-11e5-8715-7932d7d57cf7.png">

It's hard to find where your error is because the code loaded in from the blob doesn't have a map to the line number you are working on in the editor.

**Comment by enjalot** [comment]
yeah, this is because I'm inserting code before the user's code in the
iframe. We could count the lines and offset the line number given... but
can we intercept iframe errors?

We could probably add a onerror to the window inside the iframe code. it
could then postMessage the error and its metadata to the parent frame which
could then add widgets to the codemirror like we did in tributary

On Tue, Oct 13, 2015 at 12:36 PM, Geoffery Miller <notifications@github.com>
wrote:

> [image: screen shot 2015-10-13 at 3 35 43 pm]
> <https://cloud.githubusercontent.com/assets/775628/10466063/22e6b550-71c0-11e5-8715-7932d7d57cf7.png>
>
> It's hard to find where your error is because the code loaded in from the
> blob doesn't have a map to the line number you are working on in the editor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enjalot/building-blocks/issues/59>.
>



-- 
Ian Johnson - 周彦
http://enja.org

**Comment by georules** [comment]
I'll dig into it, thanks for the leads to investigate.

**Comment by georules** [comment]
Request for comments: https://github.com/georules/building-blocks/commit/65ffadb07cf0024f0dd40fd8026c423bd597254b#diff-132135bd3a692d173dafa3b21db2c06fR168

**Comment by georules** [comment]
Attaching a handler to iframe https://github.com/enjalot/building-blocks/blob/master/public/js/components/renderer.js#L71  did not seem to fire for me.  I tried iframe.contentWindow as well, but it did not fire (no complaining about any iframe sandbox security either)

**Comment by enjalot** [comment]
yeah, from what I can tell you can only listen to the errors from within
the iframe

On Thu, Oct 15, 2015 at 11:33 AM, Geoffery Miller <notifications@github.com>
wrote:

> Attaching a handler to iframe
> https://github.com/enjalot/building-blocks/blob/master/public/js/components/renderer.js#L71
> did not seem to fire for me. I tried iframe.contentWindow as well, but it
> did not fire (no complaining about any iframe sandbox security either)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enjalot/building-blocks/issues/59#issuecomment-148482434>
> .
>



-- 
Ian Johnson - 周彦
http://enja.org

**Comment by georules** [comment]
I wanted to share a prototype of this, to ask what you think about the method of implementation.  The styling needs a lot of work.  

https://github.com/georules/building-blocks/commit/66628942eabd4012c29b63604751e5b112d1cf12

https://youtu.be/8zfiCufLnHg

**Comment by enjalot** [comment]
this is great work! looks awesome so far. I shared a couple of comments in
the commit for things that I think could be improved, but I think the
fundamental approach is correct. :100:

On Sun, Oct 18, 2015 at 10:01 AM, Geoffery Miller <notifications@github.com>
wrote:

> I wanted to share a prototype of this, to ask what you think about the
> method of implementation. The styling needs a lot of work.
>
> georules@6662894
> <https://github.com/georules/building-blocks/commit/66628942eabd4012c29b63604751e5b112d1cf12>
>
> https://youtu.be/8zfiCufLnHg
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enjalot/building-blocks/issues/59#issuecomment-149030611>
> .
>



-- 
Ian Johnson - 周彦
http://enja.org

**Comment by georules** [comment]
The tooltip has some visual problems, I'm not sure why more than one is being created.  I attempted to specify which ReactTooltip to use with data-for and id's as suggested in the docs when you have more than one, but that didn't seem to help.
<img width="423" alt="screen shot 2015-10-19 at 8 58 18 am" src="https://cloud.githubusercontent.com/assets/775628/10578350/93eaa562-763f-11e5-9d92-59fb9ec8268c.png">

The version of react-tooltip we have is fairly old, I'm not sure if that's an issue.

I'm a bit new to React, and I think I'm struggling because codemirror is not a react component, and I'm trying to put react components into it.  I tried a few ways -- one way by inserting an element with data-tip into an innerHTML, but then you have to mouse over a different ReactTooltip before it will work (I think because it's not firing some kind of update/render for react when manually inserting innerHTML)
https://github.com/georules/building-blocks/commit/28bf330adcdbf316e84e04399cc6600c29a7468a#diff-54d7292f8a4b40b43aa9fad1c622303dR90

I also tried creating my own component class, but that's causing tons of components to be readded rather than reused.  
https://github.com/georules/building-blocks/commit/19b8affe59a675d470f510fd819b145b76651be2#diff-54d7292f8a4b40b43aa9fad1c622303dR97
