### ISSUE TITLE
Debugger statements not working in codemirror

### ISSUE THREAD

**Issue by sxywu** [enjalot/building-blocks#62]

**Comment by pavelloz** [comment]
@sxywu can you confirm after lately codemirror update?
I just tested at production and [it seems to work](https://www.dropbox.com/s/0m1ded1yy4jil01/Screenshot%202015-11-25%2000.31.54.png?dl=0).

**Comment by sxywu** [comment]
@pavelloz you're right!  I just tried and it is working, will close issue.
