### ISSUE TITLE
block doesn't render as expected - innerHTML issue?

### ISSUE THREAD

**Issue by micahstubbs** [enjalot/building-blocks#68]
http://blockbuilder.org/timelyportfolio/5c136de85de1c2abb6fc

http://bl.ocks.org/timelyportfolio/5c136de85de1c2abb6fc

![screen shot 2015-11-12 at 2 41 33 pm](https://cloud.githubusercontent.com/assets/2119400/11133606/8f263b1c-894b-11e5-87f2-4229c8bb24c4.png)

**Comment by enjalot** [comment]
thanks!

**Comment by micahstubbs** [comment]
:+1: this block renders great now.
