### ISSUE TITLE
Replace links at the bottom by tabs

### ISSUE THREAD

**Issue by xaranke** [enjalot/building-blocks#7]
Currently, the file-switcher is non-existent and is basically a set of links at the bottom of the page which links directly to Github. Here's what it looks like right now:
<img width="966" alt="old_file_switcher_example" src="https://cloud.githubusercontent.com/assets/1210776/9032076/6b8a549c-3980-11e5-8aa3-79d872faf010.png">

Here's what I'd like it to look like: (note that this will be at the top of the file and not the bottom, also, ignore placeholder text)
<img width="849" alt="new_file_switcher_example" src="https://cloud.githubusercontent.com/assets/1210776/9032038/0a6a85ce-3980-11e5-9822-176d29888db4.png">

I'm fairly confident that both me and @enjalot want the files to show up in the tab on clicking on them, but I'm not sure about the 'More' dropdown. 
Should we have a dropdown? Should it try to render the files locally to the best of its ability or redirect to the raw Github file like its doing right now (might be beneficial if the file is 200 MB for example)? Thoughts and suggestions greatly welcome.

Also, what tab switcher should we use? I quickly hacked up the prototypes based on the Bootstrap tab switcher, but maybe there is a better one that doesn't require importing such a huge library? 

Anything else I may not be considering? Thanks!

**Comment by enjalot** [comment]
I like the more menu. It is possible for blocks to have a ton of files (external code, multiple data files) and this keeps them neatly out of site. Eventually we will also want a :heavy_plus_sign:  button to add a new file when we are ready for the feature.

I would prefer to avoid bootstrap. We can start with simple class states for the active tab, maybe using the same simple flat style I used for the buttons. I'm still in the process of choosing a color scheme (I've just been using colors from d3.scale.category20() hehe).

**Comment by enjalot** [comment]
I just pushed an update that creates tab-like functionality. the styling is pretty whack and the functionality isn't complete, but it should help get you started.
I wanted to have the basic functionality and the code restructured into components. I'm not going to work on the file part for a while as I move on to getting the editor/rendering UI going, so feel free to take a stab if you get a chance.

**Comment by enjalot** [comment]
I think with recent code pushes, this is essentially complete. thanks for your input and help with the development!
