### ISSUE TITLE
Crashes when protocol left out

### ISSUE THREAD

**Issue by xaranke** [enjalot/building-blocks#8]
I'm not sure what is going on, but when I leave out the protocol from the include (e.g. removing the `https:` part from `https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js` to make the line `<script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>`, the program doesn't render any html.

I have a hunch this is a trivial bug, but can definitely be a showstopper for someone just trying to learn.

**Comment by enjalot** [comment]
I'm pretty sure you should always have a protocol, not sure why you would leave it out.

**Comment by xaranke** [comment]
Its an old practice from 4-5 years ago. Never mind.
