### ISSUE TITLE
[Question] Styling improvements

### ISSUE THREAD

**Issue by pavelloz** [enjalot/building-blocks#87]
I was thinking about helping by changing some CSS.
I have couple little ideas in mind that I could try to implement. 

Is visual styling open for changes/debate?

**Comment by enjalot** [comment]
yes, everything is up for debate! Depending on how much time/energy you want to invest in your experiments feel free to open a PR with suggested changes or just upload a picture/drawing/mock with your ideas and we can discuss here.

So far a lot of the styling is utilitarian and could use some love, I've been trying to make incremental improvements.

There is one important principle behind the design that I'd like to preserve: You should always be able to see what your visualization will look like in a block (e.g. 960x500px iframe)
This is the motivation for the popup functionality in the side-by-side mode that has the iframe always 960px wide and the yellow bar which is just over 500px tall.

**Comment by pavelloz** [comment]
Great, thanks. That answers my question :)
